version: "3"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "3001:8080"
    volumes:
      - ./docs/api/openapi3/schema.yml:/schema.yml
    environment:
      SWAGGER_FILE: /schema.yml
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "3002:8080"
    volumes:
      - ./docs/api/openapi3/schema.yml:/schema.yml
    environment:
      SWAGGER_YAML: /schema.yml
  swagger-api:
    image: stoplight/prism
    ports:
      - "3003:4010"
    command: mock -h 0.0.0.0 /schema.yml
    volumes:
      - ./docs/api/openapi3/schema.yml:/schema.yml
